project:
  type: website
  output-dir: docs
   

website:
  title: "jiseok_blog"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: GGS621.qmd
        text: GGS621
      - href: ITM501.qmd
        text: ITM501
      - href: sector_coupling.qmd
        text: Sector Coupling
  
  sidebar:
    style: docked
    contents: 
      - section: "PPT"
        contents:
          - href: paper_critique_slide.qmd
            text: "Paper critique GS621"
format:
  html:
    theme: cosmo
    css: styles.css

 
editor: visual

