---
title: "ITM501 - Innovation Management"
date : last-modified # now
author: 
 - name: "Jiseok AHN"
   affiliation: "KAIST"
title-block-banner: true
format: 
  html:
    theme: flatly
    code-fold: true
    toc: true
    toc-depth: 3
    toc-title: 목차
    number-sections : true
    number-depth: 2
    highlight-style: github
    self-contained: false
bibliography: references.bib

freeze: true
---

# Week 1

## Intro

-   `매주` 수업과 관련된 주요 개념 및 논문 1편 요약 제출 (분량 무관) - KLMS에 숙제 제출 및 강의자료 다운!/

    -   `금요일 자정까지 제출`

    -   모든 분들은 한 학기 2번씩 발표하게 됨 (5-7분)

    -   요약, 가설, 연구방법, 결과, 결론, 개인 의견

-   Midterm 10/21 휴강

-   **실제 시험은 11/18 or 11/25 (시험의 비중은 60%) - handwriting**

    -   서술 : 핵심 이론에 대한 설명 15문제

    -   에세이 : 주어진 기사에 숨겨있는 혁신원리, 이론을 찾아내고, 관련 현상 설명

-   **Final report**는 지금 신경 쓰지 마세요.

    -   특허 자료를 통해 수업시간에 배운 이론 실증

    -   제출 시 표절검사 결과 함께 제출 e.g., copykiller . 표절률 10\~15%까지 허용

    -   11월 정도에 기말 주제 공지 예정

## Why Do Firms Differ

-   혁신 역량의 차이

    -   디지털 경제는 기존 경제와 완전히 다르다. **디지털 기술의 속성**을 모르면 디지털 경제을 알 수 없다. 디지털은 한계체증을 한다(marginal utility, 한계체감이 제로로간다). -\> 그래서 플랫폼 기업들이 생긴다. 네이버가 고객 한명을 더 받는데 비용이 얼마나 들까? 거의 0 일것이다.

    -   테슬라가 노리는 것? 전기차 -\> OS게임. 안드로이드/IOS 처럼... 네비게이션을 사면 자동차를 주는 세상?

    -   삼천리자전거. 여태까지는 B2C에 최적화되었음. 하지만 디지털 경제의 공유사업을 통해 공유자전거가 생기고 나서 B2B가 되었음. Customer가 아닌 플랫폼 기업Business에 팔아야 하는 것임.

    -   디지털 위에서는 패러다임이 바뀐다. 그래서 기술경영이 중요. 기술(제조)과 경영.

-   혁신도 하나의 이론. Innovation Theories.

    -   세계 탑 저널은 혁신이론을 기반으로 좋은 페이퍼가 나오고 있음.

    -   **사회과학**은 누적 지식을 바탕으로 **원전(original text)**을 깔 수있음. 아담스미스의 국부론은 지금 시대에 맞지 않아! 라는 얘기 가능.

    -   혁신의 아버지 **조지프 슘페터.** 슘페터로 부터 시작. 미국 대공황. 그 시대는 사회주의 - 자본주의가 격동할 때며, 누가 정답인지 모를 때. 소련의 사회주의, 미국의 자본주의 둘 다 잘 살았고 두 체제의 우월성이 확연하지 않았음. 미국의 fordism을 다른 국가들이 보고 자본주의 체제를 따라가게 됨.

    -   케인즈 - 수요, 슘페터 - 공급. 케인즈 수요정책, 통화정책. 슘페터는 기업의 혁신. 케인즈 소득주도, 슘페터 혁신 성장론.

    -   혁신성장은 구조적으로 기업의 체질을 바꿔야 하기 때문에 효과를 보기에 오래 걸린다. 정권 초기에는 혁신 얘기를 하고, 정권 말기에는 숫자로 나타나야 하니까 수요/통화정책을 다룬다. 이념 얘기는 아니다.

    -   국가의 통화량을 얘기할 때 MV=PY. 통화량 법칙. 통화량을 높이면 GDP가 성장하는 것처럼 보인다. 국가적으로 볼 때 fake 쓰기 좋다.

        -   M: 통화량, V: 화폐유통속도(거의 상수), P:가격(물가상승률, 이자율), Y:생산량(GDP)

    -   시장은 한번도 완전한 적이 없다. 개입에 관해 결정하는 것이 정책. 정책은 어떻게 균형상태를 이끌어 갈 것인가. 시장이 실패하기 쉬운 곳에 정책이 많이 들어간다. 20년 전만 해도 자유주의 팽배하였으나, 지금은 변화함.

    -   **History of Innovation Studies 강의 슬라이드**

    -   

-   Science & Technology

-   In Social Science (Innovation study)

    -   혁신이론의 순서. 혁신연구는 과학에서 기술로 가고, 기술에서 사업화로 가야함. 과학을 통해 기술을 만들고, 기술을 통해 사업화를 이루어내야 함.

    -   과학의 주체는 어디? 대학. 과학의 측정? 논문으로. 과학을 기술로 바꾸는 역할? 기업 혹은 기업부설연구소. 기술의 측정? 특허. 출연연구소의 역할은 과학을-\> 기술로.

    -   Clarivate(Web of Science) KAIST 학생 사용 가능!! 제일 좋은 특허 사이트.

-   **다음주 숙제**

    -   **슘페터 가설이란?**

    -   **슘페터 가설과 관련된 논문 1편 요약 1p 이상**

## Homework

-   Introduction

    -   (The author's name(s) and the title of the article) Determinants of innovation in energy intensive industry and implications for energy policy, 2015년 Energy Policy에 발간된 논문[@song2015]

    -   (The author's main point) This study aims to emphasize the importance of innovation and analyze the impact of Research and Development (R&D) on both **product innovation** and **process innovation** in energy intensive industry(EII) and compare it to less EII.

    -   (A thesis statement that previews your analysis) It was Schumpeter who brought determinants of innovation into the context of mainstream economics. Schumpeter[@schumpeter1934] argued that large firms with monopolistic power in a concentrated market are more likely to promote technological innovation. This is the famous **Schumpeterian hypothesis**, which presents **firm size** and **market structure** as **the main determinants of innovation**.

-   Summary

    -   (The main points of the article) Use data from the 2008 Korea Innovation Survey to estimate the impact of key economic variables (e.g. firm size and market structure) that are proposed in the Schumpeterian hypothesis, along with other economic variables on innovation in EII.

    -   Based on the empirical results, we uncover the implications that **energy policies have on facilitating innovation in EII**.

    -   R&D will surely facilitate innovation in EII.

-   Critique

    -   (Limitations) Followed by the OECD Oslo manual, the KIS2008 measures technological innovation using a dummy variable to check whether a firm performs product or process innovations. The outputs of innovations are very **heterogeneous** in terms of quality.

    -   **The insignificant effect of market concentration** on product and process innovations in EII may be caused by the relatively short sample period.

    -   To extend the results of the study, further studies can examine this through **different analytical methods**, such as a panel regression or a Logit model.

-   Conclusion

    -   **R&D personnel ratio** has a positive and statistically significant effect on both product and process innovations. While only **R&D intensity** appears to have a significant effect on process innovation in EII. This means that for improving **process innovation,** increasing both manpower and monetary expenditures in R&D programs is necessary.

    -   **product innovation** can be enhanced by adding R&D manpower with relatively less financial investment. It is clear that process innovation is more costly and time consuming than product innovation.

    -   As for the relationship between **firm size** and innovation, interestingly, firm size has no impact on product innovation, but a positive effect on process innovation.

-   The Probit model is described as the relationship between the explanatory variables and the dependent variable that has a value of 0 or 1

**Determinants of innovation in energy intensive industry and implications for energy policy(위 homework 한글로 작성한 것임)**

-   들어가며

본 논문 분석은 슘페터 가설과 관련된 논문을 요약하는 2023년 가을학기 이노베이션 경영 1주차 과제이며, 분석 대상 논문은 에너지집약산업에서 연구개발의 영향과 혁신의 중요성을 분석한 논문으로 2015년 Energy Policy에 개제되었고 인용수는 '23년 9월 현재 89회를 기록하고 있다.

-   주요 내용요약
    -   본 연구는 연구개발(Research & Development, R&D)이 에너지집약산업(Energy Intensive Industry, EII)에서의 제품 혁신(process innovation)과 공정 혁신(process innovation)에 미치는 영향을 분석하고, 혁신의 중요성을 강조한다. 그리고 이 영향을 비 에너지집약산업과 비교한다.

    -   혁신의 결정요인을 주류 경제학으로 끌고 온 사람은 슘페터이다. 슘페터는 집중된 시장에서 독점력을 가진 대기업이 기술 혁신을 촉진할 가능성성이 높다고 주장하였다. 이는 유명한 슘페터 가설로, 기업의 규모와 시장 구조를 혁신의 주요 결정요인으로 제시하였다.

    -   2008년 한국의 기술혁신조사의 데이터를 사용하여 에너지집악산업의 혁신에 대한 경제 변수와 함께 슘페터 가설에서 제안된 주요 경제 변수(예: 기업 규모 및 시장 구조)가 혁신에 미치는 영향을 추정한다.

    -   실증적 결과를 바탕으로 우리는 에너지 정책이 에너지집약산업의 혁신 촉진에 미치는 영향을 밝히며, R&D는 에너지집약산업의 혁신을 촉진할 것이라는 점을 밝힌다.
-   결과
    -   에너지집약산업과 비에너지집약산업에 회귀분석을 수행하였고, 분석에 사용된 변수는 firm size, squared firm size, market concentration, export ratio, capital ratio, advertising intensity, R&D intensity, R&D personnel ratio로 구분된다. 분석 결과는 다음과 같이 4가지로 구분하여 제시한다.

    -   R&D 집약도와 제품 혁신, R&D 인력과 제품 혁신, R&D 집약도와 공정 혁신, R&D 인력과 공정 혁신

    -   R&D 인력 비율은 제품 및 공정 혁신 모두에 통계적으로 유의미한 영향을 미치나, R&D 집약도는 에너지집약산업의 공정 혁신에만 중요한 영향을 미치는 것으로 보인다. 이는 공정 혁신을 개선하기 위해서는 R&D 프로그램에서 인력과 금전적 지출을 모두 늘려야 함을 의미한다. 반면, 제품 혁신은 상대적으로 적은 재정 투자로 R&D 인력을 추가함으로써 강화할 수 있다. 공정 혁신이 제품 혁신보다 비용과 시간이 더 많이 소요되는 것이다.

    -   기업 규모와 혁신의 관계를 살펴보면, 흥미롭게도 기업 규모는 제품 혁신에는 영향을 미치지 않지만 공정 혁신에는 긍정적인 영향을 미친다. 큰 규모의 재정적 투자가 필요한 R&D는 중소기업들에게는 쉽지 않을 것이기 때문에, 공정 혁신을 달성하기는 보다는 제품 혁신을 달성해야 할 것이다.
-   결론
    -   OECD 오슬로 매뉴얼에 따라 KIS2008에서는 기업이 제품 혁신을 수행하는지, 공정 혁신을 수행하는지 확인하기 위해 더미변수를 사용하여 기술 혁신을 측정하였다. 이렇게 측정된 혁신의 결과는 신뢰도 측면에서 매우 이질적일 수 있다. 또한, 에너지집약산업의 혁신에 대한 시장 집중도의 미미한 영향은 상대적으로 짧은 표본 기간으로 인해 발생한 것일 수도 있다.

    -   Hermansen (2011)에 따르면 소기업과 대기업은 중기업보다 혁신을 추진하기 쉬우며, 기업의 규모에 따라 혁신활동에 미치는 영향이 다를 것이다. 향후 연구에서는 기업의 규모와 산업에 따른 혁신의 결정요인들을 분석해볼 수 있을 것이다. 또한, 패널 회귀 또는 로짓 모델과 같은 다양한 분석 방법을 통해 이를 조사를 통해 연구 결과를 확장할 수 있을 것이다.

# Week 2

## Classics of Innovation Studies

-   슘페터 가설은 정답이 없다. 그래서 여전히 논문주제로 나온다. 왜 이런 물음들이 던져진걸까..?

-   **아담 스미스** 전의 경제는 학문이 아니고, 신학과 철학, 정치 수준에 불과하였음. 수요 = 공급, 공식화 될 수 있는 걸 얘기한 사람이 아담스미스. 아담스미스가 경제**학**을만든 것임. 하나의 시장, 커뮤니티를 살펴보니 그 안에서 개인은 이기적인 마음으로 자유롭게 거래를 하는 것을 살펴봄. 모아놓고 보니 그 안에서 균형을 잡고, 전체의 후생이 증가한다는 걸 발견. **기본은 완전경쟁시장.**

-   **칼 막스**는 아담 스미스의 주장에 돌을 던짐.

-   대공황(1929, Great Depression)이 오는 원인? 수요와 공급의 사이클이 느리거나 멈췄을 때. 어디를 자극해서? 어디를 관심? 케인즈는 수요쪽. 슘페터는 공급(기업).

-   케인즈는 유효수요론 주장하면서 정부의 개입을 이야기함. - 소득주도. 왜냐하면 시장은 한번도 완전한 적이 없었기 때문. 케인즈는 기업 쪽에 관심이 없음. 수요쪽에만 관심을 가짐.

-   슘페터는 기업에서 혁신을 통해 수요 공급 사이클을 돌릴 수 있다고 말함. - 혁신성장론.

-   케인즈, 슘페터 모두 시장의 불완전성에는 동의

## Schumpeterian hypothesis

-   **Part II Can Capitalism Survive? Chapter 8 Monopolistic Practices**

::: callout-important
## 중간고사 시험 대비

-   **The Schumpeterian tradeoff revisited**[@nelson1982], **시험에 나옴!!!** **Table의 결과 정리해두면 좋을 것**

    -   기본적으로 슘페터의 가설 및 이론을 지지함.

    -   많은 경쟁자들이 있는 시장보다는 적은 경쟁자들이 있는 시장에서 혁신적인 활동이 일어나기 쉽다는 것을 보여줌.

    -   투자가 제한된 상황에서는 경쟁 시장이 혁신을 촉진하는 것 보다는 독점적 시장이 혁신을 촉진하는 것이 더 효과적임.

    -   **Table 1\~6 주요 내용 정리 필요**
:::

-   제품혁신, 공정혁신. cost reduction인지, 매출 상승인지에 따라 제품 or 공정 혁신이 달라질 수 있다.

-   first-mover와 follower의 R&D 비용 차이는 어마어마함.

## Paradigm

-   Thomas Kuhn, 패러다임의 변화. 믿음, 세계관을 포함하는 넓은 의미의 형이상학적 변화 정상과학(교과서의 변경)

-   Though the world does not change with a change of paradigm, the scientist afterwards works in a different world. "The Structure of Scientific Revolutions, p. 121."

```{mermaid}
flowchart LR 
  A(Anomalies) --> B(Crisis) 
  B(Crisis) --> C(Revolution)
  C(Revolution) --> D(Normal Science)
  D(Normal Science) --> A(Anomalies)
```

## General Purpose Technology

-   **범용기술.** 새로운 세대로의 기술적, 산업적 변화를 불러오는 혁신기술들의 최상단에 위치하는 기술로, 한 세대 산업혁명 안에서 많은 기술들의 뿌리로 인식될 수 있는 기술

-   산업혁명은 일반적으로 범용기술의 출현과 함께 시작되어 당시 산업구조의 혁신적 변화를 일으킴

-   Enabling Technology라고도 부르며, **산업간 확산성(Pervasiveness), 개선 가능성(Improvement), 혁신 촉진성(Innovation Spawning)**

## Assignment

-   **혁신의 원천 관련 논문( 공급, 수요, 사용자, 기술 디지털 등) 1편 요약**
-   혁신의 trigger, driving force? 기술인가 수요인가. source of innovation
-   Source of Innovation \[Where Don innovations Come From?\] 에 관련하여 과제를 제출하시면 됩니다.

### Sources of innovation and innovation type: firm-level evidence from the United States

-   Summary

    -   this study provides one of the first tests to identify how important sources of new information (suppliers, customers, other business people in the industry, workers, and university) are associated with types of innovations (product, process, and marketing).

    -   This article uses the first approach and treats innovation as the dependent variable while analyzing how different sources associated with overall firm innovation activity and four types of innovations.

    -   The results show that innovation ideas emanating from customers, workers, and universities are positively associated with all types of innovations, suggesting that these sources are critical for developing different types of innovation.

-   차이점

    -   our dependent variable is type of innovation and overall innovations, while most other studies focus on the amount of R&D expenditures, patent applications, location, and geographic proximity of knowledge sources

    -   data for major studies focusing on sources of innovation are mostly from the 1990s and are not current.

    -   these many studies cover only the largest R&D-performing firms, so they generally exclude smaller firms and non R&D firms, which is also true for the US Business R&D and the Innovation Survey of 2008. Our study, on the other hand, is not restricted to high-performing firms.

    -   most of the studies on innovation focus on Europe, but the focus of this study is on the United States.

-   Data and Methods

    -   Data come from the National Survey of Business Competitiveness (NSBC), which was conducted by the Social & Economic Sciences Research Center (SESRC) at Washington State University for the United States Department of Agriculture's Economic Research Service.

    -   Four different dependent variables are used in this article. (i) product(including goods and service innovations), (ii) process, (iii) marketing innovations, (iv) firm innovation activity.

-   Results

    -   the results of the unstandardized SUR models. Ideas emanating from **customers**, **workers**, and **universities** are positively associated with all types of innovations.

    -   ideas emanating from **customers** are positively associated with namely product (B = 0.06, P \< 0.001), process (B = 0.05, P \< 0.001), and marketing innovations (B = 0.05, P \< 0.001), holding other variables constant.

    -   Ideas emanating from **suppliers** are moderately and positively associated with only product innovation (B = 0.02, P \< 0.05). suppliers do not have any statistical relationship to other types of innovations.

    -   Ideas from **other business people** in the firm's industry are positively associated with process and marketing innovations (P \< 0.05), holding other variables constant, although the magnitude of the effect is small.

    -   Ideas emanating from workers are positively associated with all types of innovations (product, process, and marketing), holding other variables constant (B ¼ 0.04, 0.05, and 0.05, respectively; P \< 0.001).

    -   The universities as sources of innovation are also positively and statistically associated with both types of innovations (P \< 0.001). In fact, the university as a source of innovation has higher coefficients (B ¼ 0.07, 0.08, and 0.1, respectively), suggesting that universities are important sources of innovation.

    -   Regarding the control variables, on average, the younger firms, firms with more employees, and firms located in urban areas exhibit a greater degree of innovation activity for all types of innovations---product, process, and marketing innovations.

-   Conclusion

    -   Analyzing how five important sources of innovation (i.e. suppliers, customers, others in industry, workers, and university) are associated with types of innovation (i.e. product, process, and marketing), we have found that universities, workers, and customers are important sources of innovation positively associated with all of innovation types.

    -   Using United States National Survey of Business Competitiveness (NSBC) conducted in 2014, this study has contributed to the innovation literature by analyzing how the following knowledge sources are associated with product, process, and marketing innovation as well as overall innovation activity by the following important innovation sources: (i) suppliers, (ii) customers, (iii) other people in industry, (iv) workers, and (v) university.

    -   Universities, customers, and workers are crucial knowledge sources, positively associated with product, process, marketing, and overall innovation activity. Suppliers and others in industry have either little or no statistical effect for innovation activities.

    -   Like most of survey research, this article is based on a cross-sectional data. Therefore, lack of panel data, or quasi-experimental design does not permit scholars to make causal claims about findings. In other words, the study is correlational, not causal. In addition, due to data limitations, we could not measure which particular innovations are more important and effective than others. For example, data does not provide information about the quality of innovations such as which innovations lead huge savings, sales, or patents.

    -   We recommend future studies to focus on the link of sources and types of innovation in other context with qualitative research.

# 
